import {
  escapeHtml,
  formatDate,
  formatTimestampRange,
  formatActionItemsText,
  formatListText,
  formatCleanTranscriptText,
  formatRoleTranscriptText,
  formatRawTranscriptText,
  formatActionItemsHtml,
  formatListHtml,
  formatTranscriptRowsHtml,
  emailDocument
} from "./notes-sections.js";

export function buildTranscriptEmail({ meeting, recipient, from, includeRawEvidence = false }) {
  const subject = `Transcript: ${meeting.title}`;
  return {
    to: recipient,
    from,
    subject,
    text: formatTranscriptEmail(meeting, { includeRawEvidence }),
    html: formatTranscriptEmailHtml(meeting, { includeRawEvidence })
  };
}

export function formatTranscriptEmailHtml(meeting, { includeRawEvidence = false } = {}) {
  const notes = meeting.artifacts?.notes;
  const reconstructedTranscript = meeting.artifacts?.reconstructedTranscript;
  const normalizedSegments = meeting.artifacts?.normalizedSegments || [];
  const rawSegments = meeting.artifacts?.rawSegments || [];
  const actionItems = notes?.actionItems || [];

  return emailDocument({
    preheader: notes?.summary || "OpenNotetaker transcript and meeting notes are ready.",
    inner: `      <section class="hero">
        <p class="eyebrow">OpenNotetaker transcript</p>
        <h1>${escapeHtml(meeting.title || "Untitled meeting")}</h1>
        <div class="meta">
          ${renderMetaRow("Meet", meeting.meetUrl ? `<a href="${escapeHtml(meeting.meetUrl)}">${escapeHtml(meeting.meetUrl)}</a>` : "Not provided")}
          ${renderMetaRow("Scheduled", escapeHtml(formatDate(meeting.scheduledAt)))}
          ${renderMetaRow("Job", escapeHtml(meeting.id || "Unknown"))}
        </div>
      </section>

      <div class="grid">
        <div class="grid-row">
          ${renderStat("Actions", actionItems.length)}
          ${renderStat("Role turns", reconstructedTranscript?.turns?.length || 0)}
          ${renderStat("Clean segments", normalizedSegments.length)}
          ${renderStat("Raw segments", rawSegments.length)}
        </div>
      </div>

      <section class="section">
        <h2>Summary</h2>
        <p>${escapeHtml(notes?.summary || "No summary was generated.")}</p>
      </section>

      <section class="section">
        <h2>Action Items</h2>
        ${formatActionItemsHtml(actionItems)}
      </section>

      <section class="section">
        <div class="cards">
          <div class="card-cell">
            <h3>Decisions</h3>
            ${formatListHtml(notes?.decisions)}
          </div>
          <div class="card-cell">
            <h3>Open Questions</h3>
            ${formatListHtml(notes?.openQuestions)}
          </div>
          <div class="card-cell">
            <h3>Risks</h3>
            ${formatListHtml(notes?.risks)}
          </div>
        </div>
      </section>

      <section class="section">
        <h2>English Role-Corrected Transcript</h2>
        ${renderRoleTranscriptHtml(reconstructedTranscript)}
      </section>

      <section class="section">
        <h2>Clean English Transcript</h2>
        ${normalizedSegments.length
          ? formatTranscriptRowsHtml(
              normalizedSegments.map((segment) => ({
                speaker: segment.speaker,
                start: segment.start,
                end: segment.end,
                text: segment.english || segment.raw || ""
              }))
            )
          : "<p>No cleaned transcript was generated.</p>"}
      </section>

      ${includeRawEvidence ? `<section class="section">
        <h2>Raw Transcript Evidence</h2>
        ${rawSegments.length
          ? formatTranscriptRowsHtml(
              rawSegments.map((segment) => ({
                speaker: segment.speaker,
                start: segment.start,
                end: segment.end,
                text: segment.text || segment.raw || ""
              }))
            )
          : "<p>No raw transcript was captured.</p>"}
      </section>` : ""}

      <p class="footer">Generated by OpenNotetaker. Review transcript evidence before using notes for contracts, invoices, or commitments.</p>`
  });
}

export function formatTranscriptEmail(meeting, { includeRawEvidence = false } = {}) {
  const notes = meeting.artifacts?.notes;
  const reconstructedTranscript = meeting.artifacts?.reconstructedTranscript;
  const normalizedSegments = meeting.artifacts?.normalizedSegments || [];
  const rawSegments = meeting.artifacts?.rawSegments || [];

  return [
    meeting.title,
    "",
    `Meet: ${meeting.meetUrl}`,
    `Scheduled: ${formatDate(meeting.scheduledAt)}`,
    `Job: ${meeting.id}`,
    "",
    "SUMMARY",
    notes?.summary || "No summary was generated.",
    "",
    "ACTION ITEMS",
    formatActionItemsText(notes?.actionItems),
    "",
    "DECISIONS",
    formatListText(notes?.decisions),
    "",
    "OPEN QUESTIONS",
    formatListText(notes?.openQuestions),
    "",
    "RISKS",
    formatListText(notes?.risks),
    "",
    "ENGLISH ROLE-CORRECTED TRANSCRIPT",
    formatRoleTranscriptText(reconstructedTranscript),
    "",
    "CLEAN ENGLISH TRANSCRIPT",
    formatCleanTranscriptText(normalizedSegments),
    ...(includeRawEvidence
      ? [
          "",
          "RAW TRANSCRIPT EVIDENCE",
          formatRawTranscriptText(rawSegments)
        ]
      : [])
  ].join("\n");
}

function renderMetaRow(label, valueHtml) {
  return `<div class="meta-row"><div class="meta-label">${escapeHtml(label)}</div><div class="meta-value">${valueHtml}</div></div>`;
}

function renderStat(label, value) {
  return `<div class="stat"><strong>${escapeHtml(String(value))}</strong><span>${escapeHtml(label)}</span></div>`;
}

function renderRoleTranscriptHtml(transcript) {
  const turns = transcript?.turns || [];
  if (!turns.length) return "<p>No role-corrected transcript was generated.</p>";

  const roles = (transcript.roles || [])
    .map(
      (role) => `<div class="role-chip"><strong>${escapeHtml(role.label)}</strong>${escapeHtml(
        role.description || "No description."
      )}</div>`
    )
    .join("");
  const warnings = (transcript.warnings || []).length
    ? `<div class="warning">${formatListHtml(transcript.warnings)}</div>`
    : "";
  const rows = turns
    .map((turn) => {
      const flags = turn.flags?.length ? ` | ${turn.flags.join(", ")}` : "";
      return `<div class="turn">
        <p class="speaker-line"><span>${escapeHtml(turn.role)}</span> ${escapeHtml(formatTimestampRange(turn.start, turn.end))} | ${escapeHtml(turn.confidence || "medium")} confidence${escapeHtml(flags)}</p>
        <p class="text">${escapeHtml(turn.text || "")}</p>
      </div>`;
    })
    .join("");

  return `${roles}${warnings}${rows}`;
}
